env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "UvgSRxPnTZIC5ypFu8nzLPozWAarw3f9ZJEKaVBbQTa1dhHoEBwVutW5YJws9QzjBoKy0MRatRbMkZPJGkQGFSRgF4USnbs6SCbKOqhCVue3VjJ6T7V450AMJiD5IvvxSHStbJDDfmFYqZM/h2LKv5MOdtGqgXZLhkgL2sMUmZqi2Js0pSv9DwSFNMAvTYV6k2lnWIDVChO/cKDFM4CBKBj50nPS0UnlbuuWLExkBs31Z3zAut084kAjtGzaJJHLvU7g/DYqyPlJV8aYT43HqZeXMqeCtXkxSYTuN0sqQCvFNtB4J9E2aVR6UQyUV0t6VAqZYqO//XUnshtRvenNR3Fml9EkKlUVywHaTHRtm37l/IQteqiNa1ET9HQEnOdKGQxLck6New6sOPP33n7ZKaN+z+9s554aNAxowL7+TtVLXvTbuel2LwQUXlClW+v6/Z3KU9QESdWKAyfepgKidpyri5/SzqgLOHZVtKPnLnfkIJmEVRxL+KSyejWUTN2xi0Bh7wPeeZwK1Vh1WycIaalY6I/SAK0AEDb8IYwYhlJaoIbUSuHtGbKsXZogWK36lpYqe8wetBwIrTgqjYHWCRIRXKcybWzFDb7cvHivcUKmQ0fxLg1K/WSustb5t4CnmHbeFAriok5NW4DOW29okOfaR5KggacdctfbkuE0ZQ8="

notifications:
  irc: "chat.freenode.net#linux-wpan"

language: c

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - libnl-3-dev
    - libnl-genl-3-dev
  coverity_scan:
    project:
      name: "linux-wpan/wpan-tools"
      description: "Build submitted via Travis CI"
    notification_email: stefan@datenfreihafen.org
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

script: ./autogen.sh && ./configure && make
